#ifndef GEOSTRUCTUREALGLIB_GLOBAL_H
#define GEOSTRUCTUREALGLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef GEOSTRUCTUREALGLIB_LIB
# define GEOSTRUCTUREALGLIB_EXPORT Q_DECL_EXPORT
#else
# define GEOSTRUCTUREALGLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // GEOSTRUCTUREALGLIB_GLOBAL_H
